version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data
    environment:
      - POSTGRES_DB=postgres3
      - POSTGRES_USER=postgres3
      - POSTGRES_PASSWORD=postgres3
  web: 
    build: .
    command: python3 manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
    depends_on:
      - db 
